### ISSUE TITLE
ACC metric cant't work

### ISSUE THREAD

**Issue by lsquser** [xue-pai/FuxiCTR#25]
![image](https://user-images.githubusercontent.com/49977462/169807905-393f5707-bbbd-4db8-877e-68842248e3b0.png)
ypred is one dimension tensor,don't have the axis=1
![image](https://user-images.githubusercontent.com/49977462/169808313-35c76ef2-17bc-4aba-960f-9d599c632259.png)
In base_model.py ypred have been transform into 1 dimension

**Comment by xpai** [comment]
Thanks for raising the issue.
