### ISSUE TITLE
FNN model problem

### ISSUE THREAD

**Issue by lsquser** [xue-pai/FuxiCTR#26]
![image](https://user-images.githubusercontent.com/49977462/169808593-f17e94a0-a98c-4893-bb6b-a647eeb1ca98.png)
We can't find a function called self.reduce_learning_rate() in Base model ,does it have change into self.lr_decay()?

**Comment by lsquser** [comment]
![image](https://user-images.githubusercontent.com/49977462/169809164-d6de1ca4-b4e7-4470-a24c-5e0c43e4e323.png)

**Comment by xpai** [comment]
FNN is deleted in the current version. If you want to run FNN, you should use v1.0
