### ISSUE TITLE
EDCN bug:cross layer have no residual x_l impleted in fuxictr.layers.interaction.CrossInteraction

### ISSUE THREAD

**Issue by lsquser** [xue-pai/FuxiCTR#29]

**Comment by lsquser** [comment]
![image](https://user-images.githubusercontent.com/49977462/173299918-a881f546-e1b8-4395-8299-99893c300aaf.png)
![image](https://user-images.githubusercontent.com/49977462/173300097-8bb4294f-a1e0-4c66-b1f5-0834df555d08.png)

**Comment by zhujiem** [comment]
Thanks for reporting the issue. The benchmarking results have been updated.
| | | before | after |
|:--:|:--:|:--:|:--:|
| Criteo | AUC | 0.8148 | 0.8147 |
| | Logloss | 0.4370 | 0.4373 |
| Avazu| AUC | 0.7647 | 0.7652 |
| | Logloss | 0.3670 | 0.3670 |
| Movielens | AUC | 0.9632 | 0.9671 |
| | Logloss | 0.2666 |  0.2122 |
| Frappe| AUC | 0.9841 | 0.9850 |
| | Logloss | 0.1521 | 0.1547 |
