### ISSUE TITLE
Can you provide the config of DIN ?

### ISSUE THREAD

**Issue by paulpig** [xue-pai/FuxiCTR#32]
Hi, can you provide the config of the dataset and model about DIN on 'taobao_x1_001' ?

**Comment by Spidey0918** [comment]
Any update on this?

**Comment by xpai** [comment]
Please use the new FuxiCTR v2, https://github.com/xue-pai/FuxiCTR/tree/main/model_zoo/DIN
```
cd to model_zoo/DIN
python run_expid.py --expid DIN_test
```
This script runs DIN on the tiny data as shown in `DIN/config`.

**Comment by xpai** [comment]
The benchmark will be available soon.

**Comment by ziruizhu** [comment]
Any update for DIN's benchmark? Many thanks.
