### ISSUE TITLE
HFM may not be available due to compatibility issues

### ISSUE THREAD

**Issue by Dansheng** [xue-pai/FuxiCTR#36]
HFM adopts ```HolographicInteractionLayer```  in ```fuxictr/pytorch/layers/interaction.py```. 

However,  ```HolographicInteractionLayer``` may be not available in Pytorch 1.10 because torch.rfft/torch.irfft has changed.\

Here is a solution for reference:

```
try:
    from torch import irfft
    from torch import rfft
except ImportError:
    from torch.fft import irfft2
    from torch.fft import rfft2
    def rfft(x, d):
        t = rfft2(x, dim = (-d))
        return torch.stack((t.real, t.imag), -1)
    def irfft(x, d, signal_sizes):
        return irfft2(torch.complex(x[:,:,0], x[:,:,1]), s = signal_sizes, dim = (-d))
```

**Comment by zhujiem** [comment]
The issue has been fixed in FuxiCTR v2 and will be released soon.
