### ISSUE TITLE
训练代码epoch为100的疑问

### ISSUE THREAD

**Issue by konghr** [xue-pai/FuxiCTR#39]
您好，尝试您提供的deepFM等模型时，发现epoch为100时在criteo数据集上取得较好的效果，而推荐算法往往1个epoch就可以收敛，请问这里如何运行如此多个epoch，还能取得较好的效果？在百忙之中打扰到您~

**Comment by zhujiem** [comment]
Hi, config中的epochs是设定的最大运训的轮数，程序使用validation set做early stop，一般几个epoch达到最佳，就停止了。部分数据集1个epoch最佳。
