### ISSUE TITLE
Implementation of the model DIN

### ISSUE THREAD

**Issue by cjfcsjt** [xue-pai/FuxiCTR#4]
I am not sure whether the implementation of DIN here is consistent with the original official released code [DIN](https://github.com/zhougr1993/DeepInterestNetwork) or  [DIEN](https://github.com/mouna99/dien).
Given query_field (e.g., query Goods ID, query Cate ID) and history_field (e.g., Goods ID, Cate ID), in the original implementation, they first concatenate the embeddings of history_field (i.e., [Goods ID embedding, Cate ID embedding]) and then perform so-called "local activation unit (LAU)" with the concatenated query_field (i.e., [query Goods ID embedding,  query Cate ID embedding]). In contrast, the implementation here seems to first perform the LAU then do the concatenation. 
Specifically, the code in DIN.py:
```python
# 1. perform the LAU for each history_field
for idx, (din_query_field, din_history_field) \
            in enumerate(zip(self.din_query_field, self.din_history_field)):
            item_emb = feature_emb_dict[din_query_field]
            history_sequence_emb = feature_emb_dict[din_history_field]
            pooled_history_emb = self.attention_layers[idx](item_emb, history_sequence_emb)
            feature_emb_dict[din_history_field] = pooled_history_emb
# 2. do the concatenation here
feature_emb = self.embedding_layer.dict2tensor(feature_emb_dict)
```
If my understanding is correct, I wonder whether this will affect the final performance compared with the original implementation?

**Comment by zhujiem** [comment]
Yes, it's a good point. We are benchmarking DIN on taobao, but found the current DIN does not make big improvement on Taobao_x1. We are performing ablation studies on both versions. The plan is to update DIN to support feature concat before target attention.

Our current design is not to ,but to support mutiple sequence cases (e.g., purchase sequence, click sequence). The configuration will be:
din_query_field: [target_id, target_id]
din_history_field: [purchase sequence, click sequence]

The concation is actually the same to original DIN. It is necessary to flatten the tensor to the MLP.

The plan (this week) is to support feature concat as follows:
din_query_field: [(cate_id, target_id), (cate_id, target_id]
din_history_field: [(cate_id, purchase sequence), (cate_id, click sequence)]

But if cate_id is missing, it is equivalent to our current version. This case is consistent with the official DIN.

We found the design will also support the following case, as pointed by you.
din_query_field: [cate_id, target_id]
din_history_field: [cate_id_sequence, click sequence]

We will forward to you the performance difference later.

**Comment by zhujiem** [comment]
The model has been updated.
