### ISSUE TITLE
Many hyperlinks are no longer valid, responding with 404. Please update.

### ISSUE THREAD

**Issue by Isuxiz** [xue-pai/FuxiCTR#44]
Many hyperlinks are no longer valid, responding with 404. Please update.

For example:

In main README.md:
> 👉 See [reusable dataset splits for CTR prediction](https://github.com/openbenchmark/BARS/blob/master/ctr_prediction/datasets).

In [FuxiCTR](https://github.com/xue-pai/FuxiCTR)/[data](https://github.com/xue-pai/FuxiCTR/tree/main/data)/README.md:
> Criteo: https://github.com/openbenchmark/BARS/blob/master/ctr_prediction/datasets/Criteo
> Avazu: https://github.com/openbenchmark/BARS/blob/master/ctr_prediction/datasets/Avazu
> Taobao: https://github.com/openbenchmark/BARS/blob/master/ctr_prediction/datasets/Taobao
> KKBox: https://github.com/openbenchmark/BARS/blob/master/ctr_prediction/datasets/KKBox
> MicroVideo1.7M: https://github.com/openbenchmark/BARS/blob/master/ctr_prediction/datasets/MicroVideo1.7M
> Frappe: https://github.com/openbenchmark/BARS/blob/master/ctr_prediction/datasets/Frappe
> Movielens: https://github.com/openbenchmark/BARS/blob/master/ctr_prediction/datasets/Movielens

**Comment by xpai** [comment]
Thanks for your issue. It has been fixed now.
