### ISSUE TITLE
Problem with BN of MLP_Block in Pytorch version

### ISSUE THREAD

**Issue by LiangcaiSu** [xue-pai/FuxiCTR#52]
Hi, I found that MLP_Block didn't work properly due to BN when the length of the tensor input was greater than or equal to 3. 

Here is a toy example. 
``` 
a = torch.randn(16, 128, 64)
mlp_block = MLP_Block(input_dim=64, hidden_units=[1024,1024,1024],batch_norm=True)
mlp_block(a)
```

The output is:
```
RuntimeError: running_mean should contain 128 elements not 1024
```

**Comment by zhujiem** [comment]
MLP block only support 2d input. Please reshape the input to 2D, （16 * 128， 64）， and then input to MLP_Block?
The error is raise because BatchNorm1d and BatchNorm2d need two APIs.
