### ISSUE TITLE
[Suggestion] Automatically calculate the number of evaluation steps by setting eval_steps to less than 1.

### ISSUE THREAD

**Issue by LiangcaiSu** [xue-pai/FuxiCTR#55]
In FuxiCTRv1, eval_steps seems to be set to a float number less than 1 to support multiple evaluations within one epoch.

However, in FuxiCTRv2, eval_steps needs to manually calculate and set the number of evaluation steps.

I suggest to be able to automatically calculate the number of steps for evaluation if eval_steps is less than 1.

**Comment by xpai** [comment]
By default, when set eval_steps=None, it will be evaluated once every epoch. For multiple evaluations, the calculation is not hard? It is the common use in tf, since it is hard to get the total number of samples from tfrecord.
