### ISSUE TITLE
Any examples for numerical features?

### ISSUE THREAD

**Issue by luoda888** [xue-pai/FuxiCTR#56]
I don't find any examples for numerical + category + sequence dataset
maybe you can provide it

**Comment by xpai** [comment]
This example demonstrate category + sequence + pretrained_embs  with DIN model. https://github.com/openbenchmark/BARS/blob/main/ctr_prediction/benchmarks/DIN/DIN_microvideo1.7m_x1/DIN_microvideo1.7m_x1_tuner_config_06.yaml

**Comment by xpai** [comment]
We do not have numerical + category + sequence dataset by now for the demo.

**Comment by luoda888** [comment]
thanks, maybe you can make a demo for numerical + category + sequence for many real world datasets

**Comment by luoda888** [comment]
And I think Avazu dataset maybe use time-series split is better than random
split

xpai ***@***.***> 于2023年5月29日周一 11:55写道：
