### ISSUE TITLE
Normalizer and NaN values.

### ISSUE THREAD

**Issue by w32zhong** [xue-pai/FuxiCTR#7]
For `StandardScaler`, looks like it supports NaN values, see `class Normalizer`:
```py
null_index = np.isnan(X)
```
However, during preprocess, `_fill_na()` will fill `na_value` for non-string.
So
* for `dtype=str`, the X values will be string
* for `dtype=float/int`, the X values will be `na_value`

In the first case, `np.isnan` will throw an error because X elements are of string type.
In the second case, there is no point to normalize numbers if we have a `na_value` there.

Is this behavior expected or not?

**Comment by zhujiem** [comment]
The bug has been fixed by removing null_index = np.isnan(X)
nan values are not allowed for numeric data type. users must set na_value explicitly.
