### ISSUE TITLE
How to quickly start to train and test my new model using a public dataset instead of a toy dataset, such as avazu, criteo? 

### ISSUE THREAD

**Issue by Zeng-B-B** [xue-pai/FuxiCTR#71]
Hello, I don't know how to modify the code detailly for running my model on avazu dataset.I have three csv file(train, valid, test) for avazu, which are placed in "data" directory.which files do I need to modify?please tell me how to transform "avazu" dataset to the format(H5) we want?

**Comment by zhujiem** [comment]
Please check the benchmark links in the model table in README. Then you could find some examples to run your model. Say https://github.com/openbenchmark/BARS/tree/main/ctr_prediction/benchmarks/FinalMLP
