### ISSUE TITLE
Training on original Criterio Dataset. 

### ISSUE THREAD

**Issue by Karoljv** [xue-pai/FuxiCTR#76]
Hey, I have a question about training DeepFM on originial dataset Criterio dataset. Is this possible with the code provided in the repository? Dataset presented in demo version has 19 colummns. I mean train_sample.csv, test_sample.csv etc. Are these columns from Criterio dataset? How can I use original Criterio dataset when the data from this dataset is numerical and the caterogical columns are hashed. How to handle no labels in test set?

**Comment by zhujiem** [comment]
Please follow the benchmark steps in BARS: say  https://github.com/reczoo/BARS/tree/main/ctr_prediction/benchmarks/DeepFM/DeepFM_criteo_x1
