### ISSUE TITLE
expid repeat

### ISSUE THREAD

**Issue by lsquser** [xue-pai/FuxiCTR#8]
when i run "python run_expid.py --config /..../   --expid 191 --gpu 0" in my code,i get 2 results log .they are   ..._tune_191_ahdfy68.log and ..._tune_051_os191usd.log.In second log file name,it also has the string of '191'.

**Comment by zhujiem** [comment]
Sorry for missing your issue.

--expid should be the complete id such as "DCN_avazu_x1_010_6afb45f5". See an example here https://github.com/openbenchmark/BARS/blob/master/ctr_prediction/benchmarks/DCN/DCN_avazu_x1/DCN_avazu_x1_tuner_config_02/model_config.yaml

**Comment by lsquser** [comment]
sorry ，i write a wrong cmd which is "python run_expid.py --config /..../ --expid 191 --gpu 0".Actually,when i run "python run_param_tune.py  --config .../.. .yaml  --tags 191 --gpu 0",i get two log files.

**Comment by zhujiem** [comment]
In run_param_tuner.py, we indeed found this issue. It may occur when the hash string contain the same number. To walk around it, you may need to run with --tag _191_

The --tag specifies the substring of an expid to match.
